//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using MelonLoader;
using BlitzModIslanders;

[assembly: MelonInfo(typeof(Blitz), "ISLANDERS blitz", "1.0.0", "Sm3ip")]
[assembly: MelonGame("Coatsink", "ISLANDERS")]


// General Information about an assembly is controlled through the following
// set of attributes. Change these attribute values to modify the information
// associated with an assembly.
[assembly: AssemblyDescription("")]
[assembly: AssemblyCopyright("Copyright ©  2024")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]
[assembly: System.Reflection.AssemblyCompanyAttribute("BlitzModIslanders")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Debug")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("1.0.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("1.0.0+b77d2dd449d0f9534e9a25c4fbde897ef54bb3f7")]
[assembly: System.Reflection.AssemblyProductAttribute("BlitzModIslanders")]
[assembly: System.Reflection.AssemblyTitleAttribute("BlitzModIslanders")]
[assembly: System.Reflection.AssemblyVersionAttribute("1.0.0.0")]

// Generated by the MSBuild WriteCodeFragment class.

